- docs/DeveloperGuide.md
> Add more NFRs

- docs/DeveloperGuide.md
> Update use case for Delete

- docs/DeveloperGuide.md
> Update user profile, value proposition and user stories

- docs/DeveloperGuide.md
Added glossary for developer guide
To be continued as waiting for previous parts to be completed
> Add Glossary for DG

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
- Small change to change delete by index to delete by name (case-insensitive)
- Added string format for deletion
- (MISSING) Confirmation Prompt
- (MISSING) Duplicate Handling
> change-delete-jonus

- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
Fix issue #53 
List command can now reflect the number of contacts in list and alert user the list is empty
> Edit List Command 

- src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/TagDeleteCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/TagDeleteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/TagDeleteCommandParserTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
Notable changes include making Set<Tag> modifiable so that removeAll() can be used to update the set.
> Implemented tag-delete command

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
> Update test cases to accommodate job field

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/TagAddCommand.java
- src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
- src/main/java/seedu/address/model/person/Tag.java
- src/test/java/seedu/address/logic/commands/TagAddCommandTest.java
> Branch update output tagcommand

- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
also changed space below empty cells to pink
> Resize result display so bigger output can be seen

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Change edit to edit by name not index anymore
> Update edit command

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/ui/HelpWindow.java
- Updated the link showed by help command to Knotty planner's user guide website
- Updated user stories and target user profile
> Update help command and user stories

- docs/UserGuide.md
changed descriptions of tasks in user guide and commands
> Update userguide jonus

- src/main/java/seedu/address/logic/Messages.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> Remove duplicate method

- docs/DeveloperGuide.md
> Change dev guide

- build.gradle
- src/main/java/seedu/address/MainApp.java
> Update app name

- build.gradle
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
- src/main/java/seedu/address/logic/parser/AddWeddingCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/wedding/Datetime.java
- src/main/java/seedu/address/model/wedding/Venue.java
- src/main/java/seedu/address/model/wedding/Wedding.java
- src/main/java/seedu/address/model/wedding/WeddingName.java
- src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddWeddingCommandParserTest.java
- src/test/java/seedu/address/model/wedding/DatetimeTest.java
- src/test/java/seedu/address/model/wedding/VenueTest.java
- src/test/java/seedu/address/model/wedding/WeddingNameTest.java
- src/test/java/seedu/address/model/wedding/WeddingTest.java
- src/test/java/seedu/address/testutil/TypicalWeddings.java
- src/test/java/seedu/address/testutil/WeddingBuilder.java
- src/test/java/seedu/address/testutil/WeddingUtil.java
* Add Wedding, WeddingName, Venue, Datetime classes 
* Add AddWeddingCommand to add a new wedding with wedding name, venue and datetime
* Add Unit test to test all classes
> Add Wedding class and AddWeddingCommand

- src/test/java/seedu/address/logic/commands/FilterByJobCommandTest.java
- src/test/java/seedu/address/model/person/JobContainsKeywordsPredicateTest.java
update testing for FilterByJobCommand
> Update codecov coverage

- docs/diagrams/CommitActivityDiagram.puml
> Update UML diagram

- docs/diagrams/ArchitectureDiagram.puml
> Update architecture diagram

- docs/Documentation.md
- docs/UserGuide.md
- docs/index.md
Fixed bugs related to edit and delete command
update documentation as well
> Update UG & DG

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
- src/main/java/seedu/address/logic/commands/ClearWeddingBookCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/test/java/seedu/address/logic/commands/ClearAddressBookCommandTest.java
- src/test/java/seedu/address/logic/commands/ClearWeddingBookCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/TagAddCommandTest.java
- src/test/java/seedu/address/logic/commands/TagDeleteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Now clear command is clear address book to separate address and wedding book
> Changed clear command

- src/main/java/seedu/address/logic/commands/TagAddCommand.java
- src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
separate out the sentences to make it more readable
> Update tag add and tag delete error messages

- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/ResultDisplay.fxml
not long enough to show output without having to scroll
> Update result display size

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
edit showing wrong information for edit, not supposed to be able to edit tag
command summary also incorrect
> Update edit command to remove tag editing

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ViewWeddingCommandParser.java
- src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/ViewWeddingPanel.java
- src/test/java/seedu/address/logic/commands/ViewWeddingCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ViewWeddingCommandParserTest.java
> Implement view-wedding command

- src/main/java/seedu/address/logic/StaticContext.java
- src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
- src/main/java/seedu/address/logic/commands/ClearWeddingBookCommand.java
- src/main/java/seedu/address/logic/commands/DeleteNCommand.java
- src/main/java/seedu/address/logic/commands/DeleteYCommand.java
- src/test/java/seedu/address/logic/commands/ClearAddressBookCommandTest.java
- src/test/java/seedu/address/logic/commands/ClearWeddingBookCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteNCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteYCommandTest.java
added confirmation prompts for clear commands
all using deletey as well and staticcontext
> Change clear command

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
> Bug fix for editcommand

- src/main/java/seedu/address/logic/parser/ViewWeddingCommandParser.java
- src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/logic/commands/ViewWeddingCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ViewWeddingCommandParserTest.java
weddingKeyword is case-insensitive but has to match EXACTLY (spelling, spacing, format etc)
> Complete view-wedding implementation

- src/main/java/seedu/address/logic/commands/FilterCommand.java
> Update output messages to use static prefix imports

- src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
- src/test/java/seedu/address/logic/commands/ViewWeddingCommandTest.java
> Bug fix: Displays correct output message for weddings that are not created

- src/main/java/seedu/address/logic/commands/AddCommand.java
> Update output message for wedding doesnt exist

- src/main/java/seedu/address/logic/commands/TagAddCommand.java
> Improve Javadoc comments in TagAddCommand

- src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
> Improve Javadoc comments in TagDeleteCommand

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
- src/main/java/seedu/address/logic/parser/AddWeddingCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/wedding/Wedding.java
- src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
- src/test/java/seedu/address/logic/commands/ViewWeddingCommandTest.java
add duplicate and error handling
change user guide as well
adjust test cases as well
> Bug fix for add-wed command

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/DeleteNCommand.java
- src/main/java/seedu/address/logic/commands/DeleteWeddingCommand.java
- src/main/java/seedu/address/logic/commands/DeleteYCommand.java
- src/test/java/seedu/address/logic/commands/DeleteWeddingCommandTest.java
> Bug fix for DeleteWeddingCommand

- src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
> Update comments in ViewWeddingCommand

- src/main/java/seedu/address/ui/MainWindow.java
> Remove status bar

- src/main/java/seedu/address/ui/ResultDisplay.java
- src/main/resources/view/ResultDisplay.fxml
- src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
Modified it to now be able to resize with length of text, eliminating the need to scroll
> Change result display

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
> Addcommand alpha bug fixes

- README.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
broken command table and unclosed boxes
> fix bugs in documentation

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
> Improve EditCommand error handling

- README.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/index.md
- src/main/java/seedu/address/MainApp.java
- src/main/resources/view/MainWindow.fxml
> Standardise naming of KnottyPlanners

- README.md
- docs/UserGuide.md
- docs/index.md
> fix broken links in UG, README

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
- src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
- src/main/java/seedu/address/logic/commands/ClearWeddingBookCommand.java
- src/main/java/seedu/address/logic/commands/DeleteWeddingCommand.java
- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/commands/ListWeddingCommand.java
- src/main/java/seedu/address/logic/commands/TagAddCommand.java
- src/main/java/seedu/address/logic/commands/TagDeleteCommand.java
- src/main/java/seedu/address/logic/commands/ViewWeddingCommand.java
- src/main/java/seedu/address/model/wedding/Venue.java
- Add in explaination of CLI into user guide
> Add default command word to command with short forms

- src/main/java/seedu/address/logic/commands/DeleteYCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
> bug fix: Add in methods to allow clear-ab and clear-wb to remove wedding participants and wedding tags respectively

- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Adjust sample data and fix final checkstyle errors
> Final bug fixes

- src/main/resources/view/MainWindow.fxml
update button references correctly
> Issue with JAR file

- src/main/java/seedu/address/logic/commands/AddWeddingCommand.java
- src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java
Allowed as we catch the error but do not show the error message
> Show error message for duplicate wedding

- docs/UserGuide.md
Fixes #371 #370 #366 #360 #345 #324 #321 #320 #312 #311 #301 #298 #288 #387
> Create a parameter constraints table

- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Phone.java
- src/main/java/seedu/address/model/wedding/WeddingName.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
name and wedding names can accept `.`
phone can accept `+`
> Update regex for name to accept . and phone to acccept +

- docs/DeveloperGuide.md
> Update prefix handling in DG

- docs/DeveloperGuide.md
- docs/UserGuide.md
also fixed some spelling errors
> update global use of e.g.

- docs/DeveloperGuide.md
Fixes #291 
Fixes #326  
Fixes #334 
Fixes #346 
Fixes #349 
Fixes #351 
Fixes #354  
Fixes #363
> Improve planned enhancements in DG
